name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install jq
        
    - name: Install BATS
      run: |
        git clone https://github.com/bats-core/bats-core.git
        cd bats-core
        sudo ./install.sh /usr/local
        
    - name: Set up test environment
      run: |
        export PPLR_ROOT="${GITHUB_WORKSPACE}"
        export PPLR_BIN_DIR="${PPLR_ROOT}/bin"
        echo "PPLR_ROOT=${PPLR_ROOT}" >> $GITHUB_ENV
        echo "PPLR_BIN_DIR=${PPLR_BIN_DIR}" >> $GITHUB_ENV
        
    - name: Run tests
      run: |
        cd tests
        ./run_tests.sh
        
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.os }}
        path: tests/*.log